#!/bin/bash

TARGET=$1

RED="\033[1;31m"
GREEN="\033[1:32m"
END="\033[0m"

printf "Checking email at: ${TARGET}\n" 

printf "\nServer ip:\n"
dig $TARGET | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sed '/^127/d'
nslookup $TARGET | grep Address: | awk 'NF{ print $NF}' | sed '/^127/d'

printf "\nMail server:\n"
#nslookup -q=mx $TARGET | grep mail | awk 'NF{ print $NF}'

dig=`dig mx $TARGET +short | cut -c 3-`
for server in $dig;
do
    ipv4=`nslookup $server | grep Address: | tail -n 2 | head -n 1 | cut -d ' ' -f 2`
    ipv6=`nslookup $server | grep Address: | tail -n 1 |  cut -d ' ' -f 2`

    printf ' - %-28s IPv4: %-17s IPv6: %-20s\n' $server $ipv4 $ipv6
done

printf "\nSPF:\n"

spf=`nslookup -type=txt $TARGET | grep spf`

function getSPF() {
    nslookup -q=txt $1 | grep spf | tr ' ' '\n' | grep ip

    inc=`nslookup -type=txt $1 | sed -n -e 's/^.*\include://p' | awk '{print $1;}'`
    red=`nslookup -type=txt $1 | sed -n -e 's/^.*redirect=//p' | awk '{print $1;}' | sed 's/"$//'`

    if [ -n "$inc" ]; then
        printf "i ${inc}\n"
        getSPF $inc
    fi  
    if [ -n "$red" ]; then
        printf "r ${red}\n"
        getSPF $red
    fi
}

if [ -n "$spf" ]; then
    printf "${GREEN}FOUND${END}\n"

    printf "\nInclude & Redirect:\n"

    getSPF $TARGET
else
    printf "${RED}NOT FOUND${END}\n"
fi

printf "\n"
